config/routes.rb
Rails.application.routes.draw do
  root 'dictionaries#index'

  resources :words
  resources :dictionaries
  resources :users

  resources :user_sessions, only: [:create, :destroy]
  get 'users/confirm_email/:token', to: 'users#confirm_email', as: :confirm_email
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  belongs_to :user
  has_many :words, dependent: :destroy
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.where(user_id: current_user.id).all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
    @dictionary = set_dictionary
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
    @dictionary = set_dictionary
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to dictionaries_path, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    @dictionary = set_dictionary
      respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary = set_dictionary
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_params
      params.require(:dictionary).permit(:name, :user_id)
    end
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_form.html.slim
= form_for @dictionary do |f|
  - if @dictionary.errors.any?
    #error_explanation
      h2 = "#{pluralize(@dictionary.errors.count, "error")} prohibited this dictionary from being saved:"
      ul
        - @dictionary.errors.full_messages.each do |message|
          li = message

  .field
    b
      = f.label :name, class: 'w3-text-blue'
    = f.text_field :name, class: 'w3-input'
    = f.hidden_field :user_id, value: current_user.id
  .actions
    - if @dictionary.new_record?
      = link_to '< Back', dictionaries_path, class: 'w3-btn w3-blue'
    - else
      = link_to '< Back', @dictionary, class: 'w3-btn w3-blue'
    =< f.submit 'Save >', class: 'w3-btn w3-blue'

app/views/dictionaries/edit.html.slim
.w3-card-4
  .w3-container.w3-blue
    h2
      strong Editing dictionary - #{@dictionary.name}
  .w3-container
    == render 'form'

app/views/dictionaries/index.html.slim
.w3-card-4
  ul.w3-ul
    li
      h2
        strong.w3-text-blue Listing dictionaries
        = link_to new_dictionary_path, class: 'w3-right-align w3-right w3-large w3-text-blue w3-btn w3-hover-green w3-white' do
          i.fa.fa-plus
    - @dictionaries.each do |dictionary|
      li.w3-btn-group.w3-container
        = link_to dictionary.name, dictionary, class: 'w3-left-align w3-xlarge w3-btn-block w3-white w3-text-blue'

app/views/dictionaries/new.html.slim
.w3-card-4
  .w3-container.w3-blue
    h2
      strong New dictionary
  .w3-container
    == render 'form'

app/views/dictionaries/show.html.slim
.w3-card-4
  .w3-container
    h2
      strong.w3-text-blue Dictionary - #{@dictionary.name}
      = link_to new_word_path(dictionary_id: @dictionary.id), class: 'w3-right-align w3-right w3-large w3-text-blue w3-btn w3-hover-green w3-white' do
            i.fa.fa-plus
            i.fa.fa-file-text-o
      = link_to edit_dictionary_path(@dictionary), class: 'w3-right-align w3-right w3-large w3-text-blue w3-btn w3-hover-yellow w3-white' do
        i.fa.fa-pencil
      = link_to @dictionary, data: {:confirm => 'Are you sure?'},
        :method => :delete, class: 'w3-right-align w3-right w3-large w3-text-blue w3-btn w3-hover-green w3-white' do
        i.fa.fa-times
  .w3-container
    - @words = Word.where(dictionary_id: @dictionary.id)
    ul.w3-ul
      = render partial: 'words/index'