config/routes.rb
Rails.application.routes.draw do
  root 'dictionaries#index'

  resources :words
  resources :dictionaries
  resources :users

  resources :user_sessions, only: [:create, :destroy]
  get 'users/confirm_email/:token', to: 'users#confirm_email', as: :confirm_email
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :dictionary
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    dic_ids = Dictionary.where(user_id: current_user.id).pluck(:id)
    @words = Word.all.where(dictionary_id: dic_ids)
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = set_word
    @dictionary = @word.dictionary
  end

  # GET /words/new
  def new
    @dictionary = Dictionary.where(id: params[:dictionary_id]).first
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
    @word = set_word
    @dictionary = @word.dictionary
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)
    @dictionary = @word.dictionary

    respond_to do |format|
      if @word.save
        format.html { redirect_to @dictionary, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    @word = set_word
    @dictionary = @word.dictionary
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = set_word
    dictionary = @word.dictionary
    @word.destroy
    respond_to do |format|
      format.html { redirect_to dictionary, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:name, :dictionary_id, :translation)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.slim
  = form_for @word do |f|
    - if @word.errors.any?
      #error_explanation
        h2 = "#{pluralize(@word.errors.count, "error")} prohibited this word from being saved:"
        ul
          - @word.errors.full_messages.each do |message|
            li = message

    .field
      = f.label :name, class: 'w3-text-blue'
      = f.text_field :name, class: 'w3-input'
      = f.hidden_field :dictionary_id, value: @dictionary.id

    .field
      = f.label :translation, class: 'w3-text-blue'
      = f.text_field :translation, class: 'w3-input'
    .actions
      = link_to '< Back', words_path, class: 'w3-btn w3-blue'
      =< f.submit 'Save >', class: 'w3-btn w3-blue'

app/views/words/_index.html.slim
- @words.each do |word|
  li
    = link_to word, class: 'w3-left-align w3-xlarge w3-btn-block w3-white w3-text-blue' do
      span
        => word.name
        i.w3-text-black
          '-
          => word.translation

app/views/words/edit.html.slim
.w3-card-4
  .w3-container.w3-blue
    h2
      strong Editing word - #{@word.name}
  .w3-container
    == render 'form'

app/views/words/index.html.slim
.w3-card-4
  ul.w3-ul
    li
      h2
        strong.w3-text-blue style='width:95%'
          | Listing words
    = render partial: 'index'

app/views/words/new.html.slim
.w3-card-4
  .w3-container.w3-blue
    h2
      strong
        | New word for
        =< @dictionary.name
  .w3-container
    == render 'form'

app/views/words/show.html.slim
.w3-card-4
  .w3-container
    h2
      strong.w3-text-blue
        = @word.name
        = link_to edit_word_path(@word), class: 'w3-right-align w3-right w3-large w3-text-blue w3-btn w3-hover-yellow w3-white' do
          i.fa.fa-pencil

        = link_to @word, data: {:confirm => 'Are you sure?'},
          :method => :delete, class: 'w3-right-align w3-right w3-large w3-text-blue w3-btn w3-white w3-hover-red' do
          i.fa.fa-times
      i.w3-small
        =< "(Dictionary - #{@dictionary.name})"
  .w3-container
    b.w3-text-black.w3-xlarge
      => @word.translation