config/routes.rb
Rails.application.routes.draw do
  root 'dictionaries#index'

  resources :words
  resources :dictionaries
  resources :users

  resources :user_sessions, only: [:create, :destroy]
  get 'users/confirm_email/:token', to: 'users#confirm_email', as: :confirm_email
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.slim
.w3-container.w3-blue.w3-large.w3-hide-small.w3-hide-medium.w3-card-4.w3-padding-32.w3-opacity
  .w3-left Plums lab
  .w3-right 2016

app/views/layouts/_header.html.slim
.w3-container.w3-blue.w3-text-white.w3-card-4.w3-xlarge
  i.fa.fa-mortar-board
  | Dozen

app/views/layouts/_shared.html.slim
doctype html
html
  head
    title Dozen
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body

app/views/layouts/application.html.slim
= render partial: 'layouts/shared'
javascript:
  function w3_open() {
    document.getElementById("mySidenav").style.width = "80%";
    document.getElementById("mySidenav").style.display = "block";
  }
  function w3_close() {
      document.getElementById("mySidenav").style.display = "none";
  }

/Navbar for medium and small screens
.w3-sidenav.w3-card-4.w3-pale-blue.w3-row-padding.w3-padding-64#mySidenav style='display:none'
  a.w3-blue.w3-jumbo href='#' Menu
  = link_to '#', onclick: "w3_close()", class: 'w3-jumbo' do
    i.fa.fa-close
    =< 'Close'
  = link_to dictionaries_path, class: 'w3-jumbo'  do
    i.fa.fa-book
    =< 'Dictionaries'
  = link_to words_path, class: 'w3-jumbo'  do
    i.fa.fa-book
    =< 'Words'
  = link_to dictionaries_path, class: 'w3-jumbo'  do
    i.fa.fa-gear
    =< 'Options'
  = link_to users_path, class: 'w3-jumbo'  do
    i.fa.fa-sign-out
    =< 'Logout'

/Navbar (top panel) for large screen
.w3-top
  ul.w3-navbar.w3-blue.w3-xlarge.w3-hide-small.w3-hide-medium.w3-card-4
    li.w3-left.w3-text-white
      a.w3-hover-blue.w3-hover-text-white
        i.fa.fa-mortar-board
        | Dozen |
    li.w3-left
      = link_to dictionaries_path, class: 'w3-text-white w3-hover-white w3-hover-text-black' do
        i.fa.fa-book
        =< 'Dictionaries'
    li.w3-left
      = link_to words_path, class: 'w3-text-white w3-hover-white w3-hover-text-black' do
        i.fa.fa-book
        =< 'Words'
    li.w3-right
      = link_to sign_out_path, method: :delete, class: 'w3-text-white w3-hover-white w3-hover-text-black' do
        i.fa.fa-sign-out
        =< 'Logout'
    li.w3-right
      = link_to users_path, class: 'w3-text-white w3-hover-white w3-hover-text-black' do
        i.fa.fa-gear
        =< 'Options'

/Top panel for small and medium screen
.w3-top
  ul.w3-display-container.w3-card-4.w3-navbar.w3-blue.w3-xlarge.w3-hide-large
    li.w3-left.w3-text-white.w3-hover-text-black
      a.w3-jumbo.w3-hover-blue.w3-hover-text-white
        i.fa.fa-mortar-board
        | Dozen
    li.w3-right
      = link_to '#', onclick: "w3_open()", data: { turbolinks: false }, class: 'w3-jumbo w3-text-white w3-hover-white w3-hover-text-black'  do
        i.fa.fa-navicon

.w3-container.w3-row.w3-padding-64
  .w3-content.w3-section
    - if notice.present?
      p#notice = notice
    = yield

= render partial: 'layouts/footer'

app/views/layouts/unregistered.html.slim
= render partial: 'layouts/shared'
= render partial: 'layouts/header'

.w3-container.w3-section
  = yield

= render partial: 'layouts/footer'